### ISSUE TITLE
mkv format not available

### ISSUE THREAD

**Issue by jacobmh1177** [piergiaj/mlb-youtube#1]
It looks like the mkv format for the youtube videos is no longer available. I get the following output from running the download_videos.py script:
![image](https://user-images.githubusercontent.com/20006956/39784755-69a37342-52ce-11e8-837c-717e19e3e5ec.png)

Will another video format work, and if so, which one?

As a side-note: I'm super excited about this dataset! Thank you so much for putting it together 👍

**Comment by piergiaj** [comment]
Yeah, any format will work. There are only 20 videos, it would be quite easy to manually download them if needed. You'll just have to update the video names in the extract clips files to whatever extension you end up using. But all the video processing is handled by ffmpeg, so any format will work.

**Comment by jacobmh1177** [comment]
How about resolution? These are the options:
![image](https://user-images.githubusercontent.com/20006956/39787401-0f9f72b8-52da-11e8-86ad-c10bc7b6e3cf.png)

**Comment by piergiaj** [comment]
That depends on what you want to do. I downloaded the 1280x720 videos. However, during preprocessing, I ended up resizing all the frames to 224x224 for using in I3D or InceptionV3. The resolution depends on the CNN you're using (or whatever other method you may want).

**Comment by jacobmh1177** [comment]
Sounds good, thanks!
