### ISSUE TITLE
Some data have problem. Start time and end time are minus value.

### ISSUE THREAD

**Issue by Dondkeman** [piergiaj/mlb-youtube#13]
When I generated segmented and continuous video from mlb-youtube-segmented.json and mlb-youtube-continuous.json, I found size of some generated video are very smaller than other data. They were even uniform.

I checked json file. I could find that start time and end time of these data are minus value.
(segmented.json: 94 videos, continuous.json: 36 videos)

How did you solve this problem?

Thank you.

**Comment by acewjh** [comment]
I encountered the same issue, e.g. NTSDAE354O5W, LBRM9FRK4JTG, KGEIVDCS4A54 in the segmentated videos. This may cause a endless loop if you use "-ss -to" parameters in ffmpeg. Would you please provide the fixed annotations? Thanks :)

**Comment by ptirupat** [comment]
These are the 36 instances in continuous.json @Dondkeman  mentioned. 
WTYHRVBIUOX7
20UNPP89DK3O
0PE0DE193ZOT
U0U288GDERRH
WEFVR7T7I9E8
EL8HMREHMEJR
GV5Y3GZMC3WY
LDG91A0IDH70
FYJN3C3RHFKA
N16B2W11GVQV
2Y3R4WE1J6UK
Z9R1F41QWDJX
QBRR0ZZ8TR4N
WJBVXWHVYECI
3MO2VOZ69SOU
87W74VYXB4JQ
LT5TMMO0VIAI
LPYLYUDA6Q8R
T2FDQBS4CYQF
VXQZLVQXGSB1
GBSFY5916XV6
YE89948YLFY3
09I604OYI10U
55XSIZHOABJC
FUAEFLBC9M59
C2WPMYXUQMRE
C036XD13X6X9
UI4JUYMJ9FGC
550J0HSRTL2E
S4F2MEMO5D6P
8SY9UOITR2J9
DYS6DQDE5PWG
7HL3BX78KNA2
SOK75042V0ZO
EZPBZJP1FMWC
P6ZTUO4N6C3E

**Comment by Dondkeman** [comment]
I sol

**Comment by Dondkeman** [comment]
I solved.

`     command = ['ffmpeg',
                '-i', '"%s"' % filename,
                '-ss', time.strftime('%H:%M:%S', time.gmtime(start_time)),
                '-t', str(duration),
                '-c:v', 'copy', '-an',
                '-threads', '1',
                '-loglevel', 'panic',
                '-framerate', '60',
                os.path.join(output_directory,output_filename)]
`
