### ISSUE TITLE
Video Loader

### ISSUE THREAD

**Issue by jacobmh1177** [piergiaj/mlb-youtube#2]
From your video loader it looks like you converted all the video files to numpy arrays.
Is that correct? And, if so, how much memory did that take up?

**Comment by piergiaj** [comment]
Yes, I extracted per-frame I3D and inceptionV3 features and saved those as numpy arrays. The segmented videos takes about 8GB(I3D)/10GB(inception) for a single stream (16GB/20GB for both RGB and optical flow features).
