### ISSUE TITLE
download_videos.py error fixed

### ISSUE THREAD

**Issue by a258sa258s** [piergiaj/mlb-youtube#3]
error:
yturl = entry['url']

fixed:
yturl = data[entry]['url']

**Comment by a258sa258s** [comment]
what is "in play" meaning?

**Comment by piergiaj** [comment]
In play is the a ball that is hit “in play,” so not a foul ball. The “hit” activity is broken into “foul” and “in play” activities. This is a bit different from the standard baseball definition of “hit.”

On Jun 7, 2018, at 5:13 AM, a258sa258s <notifications@github.com<mailto:notifications@github.com>> wrote:


what is in play meaning?

**Comment by a258sa258s** [comment]
thank you
