### ISSUE TITLE
Error: run the experiments/train_segmented.py

### ISSUE THREAD

**Issue by jhj7905** [piergiaj/mlb-youtube#5]
hi @piergiaj 
i extracted video clip with extract_segmented_videos.py
now, i trained the network with train_segmented.py 
but error occured like below
python experiments/train_segmented.py 
lb-youtube-negative.json', 'training', '/')
  File "/home/hyunjo/mlb-youtube/experiments/segmented_dataset.py", line 55, in __init__
    n["labels"] = []
TypeError: 'str' object does not support item assignment

i think it is related to #4 
now source code is below
class SegmentedPitchResultMultiLabel(data_utl.Dataset):
    """
      0 - ball
      1 - swing
      2 - strike
      3 - hit
      4 - foul
      5 - in play
      6 - bunt
      7 - hit by pitch
    """

    def __init__(self, positive, negative, split, root):
        self.root = root
        with open(positive, 'r') as f: 
            self.act_dict = json.load(f)
            for a in self.act_dict.keys():
                if self.act_dict[a]['subset'] != split:
                    del self.act_dict[a]
            
        with open(negative, 'r') as f:
            self.negs = json.load(f)
        for n in self.negs:
            n['labels'] = []
            self.act_dict.append(n)
        self.videos = self.act_dict.keys()
        
    def __getitem__(self, index):

how do i modify it?
thank you in advance

**Comment by piergiaj** [comment]
This should fix it:

```python
for n in self.negs.keys():
    self.negs[n]['labels'] = []
    self.act_dict[n] = self.negs[n]
```

**Comment by jhj7905** [comment]
Hi @piergiaj 

i fixed it but.. still error occured..

python experiments/train_segmented.py -mode rgb
Namespace(dataset='i3d', flow_model_file=None, gpu=1, mode='rgb', model_file=None, rgb_model_file=None, train=True)
Traceback (most recent call last):
  File "experiments/train_segmented.py", line 58, in <module>
    pin_memory=True, collate_fn=sd.collate_fn)
AttributeError: module 'segmented_dataset' has no attribute 'collate_fn

there is not sd.collate_fn in your code

can you tell me how to fix it?

thank you in advance

**Comment by piergiaj** [comment]
I forgot to add the collate function to the script. I added it now.

For reference:

```python
def collate_fn(batch):
    "Pads data and puts it into a tensor of same dimensions"
    max_len = 0
    for b in batch:
        if b[0].shape[0] > max_len:
            max_len = b[0].shape[0]

    new_batch = []
    for b in batch:
        f = np.zeros((max_len, b[0].shape[1], b[0].shape[2], b[0].shape[3]), np\
.float32)
        m = np.zeros((max_len), np.float32)
        l = b[1]
        f[:b[0].shape[0]] = b[0]
        m[:b[0].shape[0]] = 1
        new_batch.append([video_to_tensor(f), torch.from_numpy(m), l, b[2]])
    return default_collate(new_batch)
```

**Comment by jhj7905** [comment]
@piergiaj 

thank you i add it !! but still error occured like below

python experiments/train_segmented.py -mode rgb
Namespace(dataset='i3d', flow_model_file=None, gpu=1, mode='rgb', model_file=None, rgb_model_file=None, train=True)
Epoch 0/9
----------
Traceback (most recent call last):
  File "experiments/train_segmented.py", line 163, in <module>
    train_model(model, criterion, optimizer, num_epochs=10)
  File "experiments/train_segmented.py", line 93, in train_model
    for data in dataloaders[phase]:
  File "/home/hyunjo/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/hyunjo/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/hyunjo/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hyunjo/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hyunjo/mlb-youtube/experiments/segmented_dataset.py", line 68, in __getitem__
    name = self.videos[index]
TypeError: 'dict_keys' object does not support indexing


def __getitem__(self, index):
        """
        Args:
            index (int): Index

        Returns:
            tuple: (image, target) where target is class_index of the target class.
        """
        name = self.videos[index]
        label = self.act_dict[name]['labels']

        path = os.path.join(self.root, name+'.npy')
        multilabel = np.zeros((8,))

        img = np.load(path)
        if img.shape[-1] == 1024:
            feat = img[np.random.randint(0,10)]
        if len(label) > 0:
            for labs in label:
                multilabel[l2i[labs]] = 1

        return feat, multilabel, name

how to fix it?

**Comment by piergiaj** [comment]
Which version of python are you using? I was using 2.7 for this project, I'm guessing you're using 3. If so, there's some slight difference in how dictionaries are treated.

To make this work with python 3, change the line where the video list is created:

```
self.videos = list(self.act_dict.keys())
```

Note, there may be other issues with python 3, since I haven't tested this code with it yet.

**Comment by jhj7905** [comment]
@piergiaj 
I am using python 3. so i had better use python2.7 to run your code.
Anyway. can you tell me the whole process to train the network?
1. download_videos.py
2. extract_segmented_videos.py
3. tain_segmented.py
Can you tell me the whole process in details???

one more thing!
how do i convert frame to numpy??
when i ran the "train_segmented.py" the error occured like below
  File "experiments/train_segmented.py", line 163, in <module>
    train_model(model, criterion, optimizer, num_epochs=10)
  File "experiments/train_segmented.py", line 93, in train_model
    for data in dataloaders[phase]:
  File "/home/hyunjo/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/hyunjo/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
./segmented
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/home/hyunjo/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hyunjo/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hyunjo/mlb-youtube/experiments/segmented_dataset.py", line 76, in __getitem__
    img = np.load(path)
  File "/home/hyunjo/anaconda3/envs/pytorch/lib/python3.6/site-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './segmented/CN5F864EXDZU.npy'


i think it did not make numpy file
how to fix it?
thank you in advance

**Comment by piergiaj** [comment]
To get the numpy files, you have to extract the features. Included in the pytorch-i3d directory is the extract_features.py script I used to convert the videos to I3D features and save as numpy arrays.

Though you can use any CNN to obtain the features and save the numpy arrays.
