### ISSUE TITLE
Is the code of TGM in your best performing model 'I3D + super-event [4] + 3 TGM [5]' on continuous video activity detection available?

### ISSUE THREAD

**Issue by Yingyan-Xu** [piergiaj/mlb-youtube#8]
Hello! @piergiaj 
I have been recently researching on your excellent papers about activity detection. I would be appreciated if you could upload your code for TGM, whose results are listed in README.

**Comment by piergiaj** [comment]
We will be releasing the code once the TGM paper is published (which likely won't be for ~6 months, unfortunately). If you send me an email, I might be able to help you.
